---
- name: Install packages required to build ruby.
  yum: "pkg={{ item }} state=installed"
  with_items:
    - zlib-devel
    - openssl-static

- name: Download specific ruby version.
  get_url: >
    url={{ ruby_download_url }}
    dest={{ build_directory }}/ruby-{{ ruby_version }}.tar

- name: Extract ruby to build directory.
  command: >
    tar -zxf {{ build_directory }}/ruby-{{ ruby_version }}.tar
    chdir={{ build_directory }}
    creates={{ build_directory }}/ruby-{{ ruby_version }}

- name: Build ruby from package.
  command: >
    {{ item }}
    chdir={{ build_directory }}/ruby-{{ ruby_version }}
    creates=/usr/local/bin/ruby
  with_items:
    - ./configure --enable-shared
    - make
    - sudo make install

- name: Add ruby symlinks.
  file: >
    src=/usr/local/bin/{{ item }}
    dest=/usr/bin/{{ item }}
    state=link
    force=yes
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby
